//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Editor automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.DomIds
{
	using System;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;

	public static class Github_Repositories
	{
		public const string ModuleId = "github_repositories";
		public static class Enums
		{
			public enum Workflowtype
			{
				AutomationScriptCI = 0,
				AutomationScriptCICD = 1
			}
		}

		public static class Sections
		{
			public static class FillInAutomationScriptCICDInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("53a64c0d-a1d7-4820-8342-077688b869c5"))
				{ ModuleId = "github_repositories" };
				public static FieldDescriptorID SonarCloudProjectID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("b1647abf-6b23-44a9-a72c-aa70050b8e11"));
				public static FieldDescriptorID DataminerDeployKey
				{
					get;
				}

				= new FieldDescriptorID(new Guid("61938125-373d-4a45-aca5-5ff45b98a52f"));
			}

			public static class ChooseWorkflow
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("b63e5276-9081-4cbb-bc1e-ba8b6eea357f"))
				{ ModuleId = "github_repositories" };
				public static FieldDescriptorID DataminerID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("ab2ec361-28e8-4026-962d-adb9ce316b4b"));
				public static FieldDescriptorID ElementID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("4fa00c67-b60e-4e2c-aba1-36494e524291"));
				public static FieldDescriptorID RepositoryID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("55c763e0-f062-49a4-bf6b-172d2afa77b9"));
				public static FieldDescriptorID Workflow
				{
					get;
				}

				= new FieldDescriptorID(new Guid("01969f7e-a1a7-4c34-bcc9-d6f966be0f49"));
			}

			public static class FillInAutomationScriptCIInformation
			{
				public static SectionDefinitionID Id
				{
					get;
				}

				= new SectionDefinitionID(new Guid("0d6a500b-dca7-4635-92c1-400304908b4e"))
				{ ModuleId = "github_repositories" };
				public static FieldDescriptorID SonarCloudProjectID
				{
					get;
				}

				= new FieldDescriptorID(new Guid("a0067c3d-a140-4879-b18c-777ac7c64c7d"));
				public static FieldDescriptorID DataminerDeployKey
				{
					get;
				}

				= new FieldDescriptorID(new Guid("82d0b05f-93ea-472a-a3d7-d0c8983cd18a"));
			}
		}

		public static class Definitions
		{
			public static DomDefinitionId AddWorkflow
			{
				get;
			}

			= new DomDefinitionId(new Guid("756cfb61-14ba-4c2a-aed8-24824b1c9b4e"))
			{ ModuleId = "github_repositories" };
		}

		public static class Behaviors
		{
			public static class AddWorkflow
			{
				public static DomBehaviorDefinitionId Id
				{
					get;
				}

				= new DomBehaviorDefinitionId(new Guid("450a6634-a22a-4568-9985-4671d48816d4"))
				{ ModuleId = "github_repositories" };
				public static class Statuses
				{
					public const string ChooseWorkflow = "ac13ed18-cbf7-4cce-8e06-ba96fd751d1f";
					public const string FillInAutomationScriptCIInformation = "7e787332-2517-40ff-95d9-fc503eb6bc55";
					public const string FillInAutomationScriptCICDInformation = "116ea04c-e7f2-4032-8a59-8a958243e97b";
					public const string Completed = "d5add7c5-d1fe-4dc4-b0f8-c7a22d43735e";
				}

				public static class Transitions
				{
					public const string ToAutomationScriptCi = "to-automation-script-ci";
					public const string ToAutomationScriptCicd = "to-automation-script-cicd";
					public const string FromAutomationScriptCi = "from-automation-script-ci";
					public const string FromAutomationScriptCicd = "from-automation-script-cicd";
					public const string FromAutomationScriptCiToCompleted = "from-automation-script-ci-to-completed";
					public const string FromAutomationScriptCicdToCompleted = "from-automation-script-cicd-to-completed";
				}
			}
		}
	}
}