// <auto-generated>This is auto-generated code by https://json2csharp.com/. Do not modify.</auto-generated>
namespace Skyline.DataMiner.Github.Repositories.Helpers
{
	using System;
	using System.Collections.Generic;

	using Newtonsoft.Json;

	// Root myDeserializedClass = SecureNewtonsoftDeserialization.DeserializeObject<SonarCloudProjectComponentResult>(myJsonResponse);
	public class Alm
	{
		[JsonProperty("key")]
		public string Key { get; set; }

		[JsonProperty("url")]
		public string Url { get; set; }
	}

	public class Breadcrumb
	{
		[JsonProperty("key")]
		public string Key { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("qualifier")]
		public string Qualifier { get; set; }
	}

	public class Configuration
	{
		[JsonProperty("showSettings")]
		public bool ShowSettings { get; set; }

		[JsonProperty("showQualityProfiles")]
		public bool ShowQualityProfiles { get; set; }

		[JsonProperty("showQualityGates")]
		public bool ShowQualityGates { get; set; }

		[JsonProperty("showManualMeasures")]
		public bool ShowManualMeasures { get; set; }

		[JsonProperty("showLinks")]
		public bool ShowLinks { get; set; }

		[JsonProperty("showPermissions")]
		public bool ShowPermissions { get; set; }

		[JsonProperty("showHistory")]
		public bool ShowHistory { get; set; }

		[JsonProperty("showUpdateKey")]
		public bool ShowUpdateKey { get; set; }

		[JsonProperty("showBackgroundTasks")]
		public bool ShowBackgroundTasks { get; set; }

		[JsonProperty("canApplyPermissionTemplate")]
		public bool CanApplyPermissionTemplate { get; set; }

		[JsonProperty("canBrowseProject")]
		public bool CanBrowseProject { get; set; }

		[JsonProperty("canViewCode")]
		public bool CanViewCode { get; set; }

		[JsonProperty("canScanProject")]
		public bool CanScanProject { get; set; }

		[JsonProperty("canUpdateProjectVisibilityToPrivate")]
		public bool CanUpdateProjectVisibilityToPrivate { get; set; }
	}

	public class QualityGate
	{
		[JsonProperty("key")]
		public int Key { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("isDefault")]
		public bool IsDefault { get; set; }
	}

	public class SonarCloudProjectComponentResult
	{
		[JsonProperty("key")]
		public string Key { get; set; }

		[JsonProperty("organization")]
		public string Organization { get; set; }

		[JsonProperty("organizationName")]
		public string OrganizationName { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("isFavorite")]
		public bool IsFavorite { get; set; }

		[JsonProperty("badgeToken")]
		public string BadgeToken { get; set; }

		[JsonProperty("createdAt")]
		public DateTime CreatedAt { get; set; }

		[JsonProperty("visibility")]
		public string Visibility { get; set; }

		[JsonProperty("alm")]
		public Alm Alm { get; set; }

		[JsonProperty("qualityProfiles")]
		public List<object> QualityProfiles { get; set; }

		[JsonProperty("qualityGate")]
		public QualityGate QualityGate { get; set; }

		[JsonProperty("configuration")]
		public Configuration Configuration { get; set; }

		[JsonProperty("breadcrumbs")]
		public List<Breadcrumb> Breadcrumbs { get; set; }
	}
}
