// Ignore Spelling: Github

namespace Skyline.DataMiner.Github.Repositories.Views.Explanations
{
	using System.Text;

	using Skyline.DataMiner.Automation;

	public class SonarCloudTokenView : ExplanationInputView
	{
		public SonarCloudTokenView(IEngine engine) : base(engine, "Sonar Cloud Token")
		{
			var explanation = new StringBuilder();
			explanation.AppendLine("A new Sonar Cloud Token can be generated by going to sonarcloud.io, and creating a new one for this repository.");
			explanation.AppendLine("Go to https://sonarcloud.io/account/security if you don't have a token already.");
			explanation.AppendLine("1. Enter the name of the repository in the Generate Token textbox");
			explanation.AppendLine("2. Click on the 'Generate Token' button");
			explanation.AppendLine("3. Copy the generated token");
			explanation.AppendLine("4. Paste the token in the below textbox.");
			Explanation.Text = explanation.ToString();
		}
	}
}
